import { useState } from "react";
import type { Quiz, QuizRequest } from "./types";
import { fetchQuiz } from "./api";
import { SetupForm } from "./components/SetupForm";
import { QuizView } from "./components/QuizView";
import { Results } from "./components/Results";

type Stage = "setup" | "quiz" | "results";

export function App() {
  const [stage, setStage] = useState<Stage>("setup");
  const [quiz, setQuiz] = useState<Quiz | null>(null);
  const [score, setScore] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function startQuiz(req: QuizRequest) {
    setLoading(true);
    setError(null);
    try {
      const result = await fetchQuiz(req);
      if (result.questions.length === 0) {
        throw new Error("No questions came back. Try a different topic.");
      }
      setQuiz(result);
      setStage("quiz");
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error.");
    } finally {
      setLoading(false);
    }
  }

  function finishQuiz(finalScore: number) {
    setScore(finalScore);
    setStage("results");
  }

  function restart() {
    setQuiz(null);
    setScore(0);
    setStage("setup");
  }

  return (
    <div className="app">
      <header className="header">
        <h1>✨ Spark</h1>
        <p className="tagline">A dynamic learning app powered by AI</p>
      </header>

      <main>
        {stage === "setup" && (
          <>
            <SetupForm loading={loading} onStart={startQuiz} />
            {error && (
              <p className="error" role="alert">
                {error}
              </p>
            )}
          </>
        )}

        {stage === "quiz" && quiz && (
          <>
            <p className="source-note">
              {quiz.source === "ai"
                ? "Questions freshly generated by AI ✨"
                : "Questions from the offline practice set"}
            </p>
            <QuizView quiz={quiz} onFinish={finishQuiz} />
          </>
        )}

        {stage === "results" && quiz && (
          <Results
            score={score}
            total={quiz.questions.length}
            onRestart={restart}
          />
        )}
      </main>

      <footer className="footer">
        <span>Made for curious kids and the grown-ups who teach them.</span>
      </footer>
    </div>
  );
}
